run:
  deadline: 5m
  skip-dirs:
    - demos
linters:
  enable-all: true
  disable:
    - varnamelen
    - exhaustruct
    # deprecated
    - structcheck
    - deadcode
    - varcheck
    - nosnakecase
    - ifshort
    - golint
    - maligned
    - interfacer
    - scopelint
    - exhaustivestruct
linters-settings:
  errcheck:
    check-blank: false
    ignore: fmt:.*
  nolintlint:
    require-specific: true
