name: Go
on:
  push:
    branches: [ main ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'
      - uses: actions/checkout@v4
      - run: |
          dnf -y install make
          make .install.golangci-lint
          make lint
