name: validate pull requests
on:
  pull_request:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: get pr commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: DCO check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}

      - name: check subject line length
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.{0,72}(\n.*)*$'
          error: 'Subject too long (max 72)'

  codespell:
    name: codespell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ./.git,./vendor,*_test.go,go.sum,go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'
      - uses: actions/checkout@v4
      - run: |
          dnf -y install make
          make .install.golangci-lint
          make lint

  goreportcard:
    name: update reportcard
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0
